sonar.projectKey=augustocristian_samples-python-template
sonar.organization=augustocristian
sonar.python.coverage.reportPaths=coverage-unit/coverage.xml
sonar.sources=.
sonar.exclusions=**/tests/**,.git/**
sonar.python.version=3.12
# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=samples-python-template
#sonar.projectVersion=1.0
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8